[workspace]
resolver = "2"
members = [
  "apps/backend",
  "packages/tauri-plugin-dwm",
]

[workspace.package]
authors = ["deminearchiver"]
edition = "2021"
license = "ISC"

[workspace.dependencies]
tauri-plugin-dwm = { path = "packages/tauri-plugin-dwm" }
