[package]
name = "tauri-plugin-ftp"
version = "0.0.0"
authors.workspace = true
description = ""
edition.workspace = true
links = "tauri-plugin-ftp"

[dependencies]
tauri = { version = "2.0.0-beta" }
serde = "1.0"
thiserror = "1.0"

ftp = "3.0"
url = "2.5"

[build-dependencies]
tauri-plugin = { version = "2.0.0-beta", features = ["build"] }
