name: Build application
run-name: Building application

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "apps/**"
      - "!apps/docs/**"
      - "packages/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn workspace @blending/backend build
      - uses: actions/upload-artifact@v4
        with:
          name: blending-windows-portable
          path: |
            target/release/resources/
            target/release/blending.exe
            target/release/blending.pdb
            target/release/blending.d
      - uses: actions/upload-artifact@v4
        with:
          name: blending-windows-bundle
          path: target/release/bundle/
